services:
  headoo.medias.manager:
          class: Headoo\MediaSocialApiBundle\Services\Manager\SocialMediasManager
          arguments:
            - "@headoo.twitter.tweet_manager"
            - "@headoo.instagram.manager"

  headoo.twitter.tweet_manager:
          class: Headoo\MediaSocialApiBundle\Services\Manager\TweetManager
          arguments:
            - %headoo_media_social_api.twitter_access.oauth_access_token%
            - %headoo_media_social_api.twitter_access.oauth_access_token_secret%
            - %headoo_media_social_api.twitter_access.consumer_key%
            - %headoo_media_social_api.twitter_access.consumer_secret%

  headoo.instagram.manager:
          class: Headoo\MediaSocialApiBundle\Services\Manager\InstagramManager
          arguments:
            - %headoo_media_social_api.instagram_access.access_token%